services:
  db:
    image: postgres:16.8
    env_file:
      - ../../.env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile.dev
    env_file:
      - ../../.env
    environment:
      PG_HOST: db
    depends_on:
      - db
    volumes:
      - ../../logs:/app/logs
      
    
