FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    build-essential \
    libpq-dev \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements/ /app/requirements

RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements/dev.txt

COPY . /app

CMD ["bash", "/app/scripts/entrypoint.sh"]
