version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  bot:
    image: moses93/telegram-bot:latest
    env_file:
      - .env
    depends_on:
      - db
    
volumes:
  postgres_data: