"""upda_new_field user_id

Revision ID: 12f14f8cef2f
Revises: 1e4c453220b7
Create Date: 2024-10-15 19:19:14.583851

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12f14f8cef2f"
down_revision: Union[str, None] = "1e4c453220b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_main_notes_user_id", table_name="main_notes")
    op.create_index(
        op.f("ix_main_notes_user_id"), "main_notes", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_main_notes_user_id"), table_name="main_notes")
    op.create_index("ix_main_notes_user_id", "main_notes", ["user_id"], unique=True)
    # ### end Alembic commands ###
