"""added reminder_hours field to Notes

Revision ID: a9f695071c0e
Revises: 7ffae9dd75c6
Create Date: 2024-10-23 12:45:03.733219

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a9f695071c0e"
down_revision: Union[str, None] = "7ffae9dd75c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "main_notes", sa.Column("reminder_hours", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("main_notes", "reminder_hours")
    # ### end Alembic commands ###
