"""added_column_restrictions_and_changed

Revision ID: ae0b300ca21d
Revises: 
Create Date: 2024-11-24 10:55:23.694780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ae0b300ca21d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "main_dates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("free", sa.Boolean(), nullable=True),
        sa.Column("del_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_main_dates_free"), "main_dates", ["free"], unique=False)
    op.create_index(op.f("ix_main_dates_id"), "main_dates", ["id"], unique=False)
    op.create_table(
        "main_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("durations", sa.Interval(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_main_services_id"), "main_services", ["id"], unique=False)
    op.alter_column("main_notes", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("main_notes", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "main_notes", "time", existing_type=postgresql.TIME(), nullable=False
    )
    op.create_foreign_key(
        None, "main_notes", "main_services", ["service_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "main_notes", "main_dates", ["date_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "main_notes", type_="foreignkey")
    op.drop_constraint(None, "main_notes", type_="foreignkey")
    op.alter_column(
        "main_notes", "time", existing_type=postgresql.TIME(), nullable=True
    )
    op.alter_column("main_notes", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("main_notes", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_index(op.f("ix_main_services_id"), table_name="main_services")
    op.drop_table("main_services")
    op.drop_index(op.f("ix_main_dates_id"), table_name="main_dates")
    op.drop_index(op.f("ix_main_dates_free"), table_name="main_dates")
    op.drop_table("main_dates")
    # ### end Alembic commands ###
