"""change type column type in Notes

Revision ID: b091597e4bb7
Revises: 12f14f8cef2f
Create Date: 2024-10-20 13:58:06.425129

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b091597e4bb7"
down_revision: Union[str, None] = "12f14f8cef2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.alter_column(
        "main_notes", "time", type_=sa.Time(), postgresql_using="time::time"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "main_notes",
        "time",
        existing_type=sa.Time(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
