name: CI/CD Pipeline


on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test
          POSTGRES_DB: postgres
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up environment variables
        run: |
          echo "TOKEN"=${{secrets.TOKEN}} >> .env
          echo "SENDERS_TOKEN"=${{secrets.SENDERS_TOKEN}} >> .env
          echo "URI="${{secrets.URI}} >> .env
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Run tests
        run: |
          pytest