name: CI/CD Pipeline


on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3
      
      - name: Install dependencies
        env:
          URI: "postgresql+asyncpg://postgres:test@127.0.0.1:5432/postgres"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Run tests
        run: |
          pytest