name: CI/CD Pipeline


on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up environment variables
        run: |
          echo "TOKEN"=${{secrets.TOKEN}} >> .env
          echo "SENDERS_TOKEN"=${{secrets.SENDERS_TOKEN}} >> .env
          echo "URI="${{secrets.URI}} >> .env
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Run tests
        run: |
          pytest
    
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t moses93/telegram-bot:latest .
      
      - name: Log in to Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
      - name: Push Docker image
        run: |
          docker push moses93/telegram-bot:latest
      
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME }}
          key: ${{secrets.SSH_KEY}}
          script:
            chmod +x app/chashurina-brows-bot/deploy.sh
            app/chashurina-brows-bot/deploy.sh


          